# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: test

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

env:
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  CF_API_SECRET: ${{ secrets.CF_API_SECRET }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test and generate coverage 
      run: go test . -race -coverprofile=coverage.out -covermode=atomic

    # This is marked optional because if we send too many requests
    # the API might return a 503. This has to be considered an error in 
    # actual production code, but the CI shouldn't report fake failures
    # since it's misleading. 
    - name: Test and generate coverage (Integration)
      continue-on-error: true
      run: go test . -tags=integration -race -coverprofile=coverage.out -covermode=atomic

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
